### ISSUE TITLE
Spectrum should display only wavelength values in the cube

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#137]
When I load the MaNGA cube, the spectral display starts at wavelengths < 0 even though the MaNGA spectrum doesn't start until 0.35 x 10 ^-6:

<img width="1371" alt="screen shot 2017-12-12 at 12 08 08 am" src="https://user-images.githubusercontent.com/11748049/33873619-93181970-ded0-11e7-8d0b-293c9a55685e.png">

**Comment by nmearl** [comment]
This has been fixed (awhile ago I believe). The initial position of the wavelength selection vertical line (the green line) is now determined by the current wavelength value selected in cubeviz.

**Comment by brechmos-stsci** [comment]
This is still an issue.  The problem is the left hand side and right hand side of the spectral views in cubeviz.  The desire is for the first point in the wavelength spectrum to be at the left hand edge of the spectral plot and for the last point in the wavelength spectrum to be at the right hand edge of the spectral plot.

![screen shot 2018-03-14 at 8 06 34 am](https://user-images.githubusercontent.com/18348847/37401589-ed6aa88a-275e-11e8-9548-54a953627700.jpeg)

**Comment by nmearl** [comment]
@brechmos-stsci this isn't the original issue which was that the wavelength range starts at a point < 0. This was due to the wavelength vertical line selector being initialized at 0 on the plot, thus dragging the range lower than it needed to be.

The case you're point out I don't really see as an issue; zooming or dragging the spectrum around is going to, by its nature, expose ranges beyond the edges of the spectrum.

**Comment by kassin** [comment]
When I change the wavelength units, the beginning and start wavelength values displayed do not correspond at all to the spectrum.  Sometimes the spectrum isn't even displayed.

**Comment by nmearl** [comment]
@kassin When you change the units from cubeviz, or from within specviz (or do they both cause the same issue)?

**Comment by kassin** [comment]
@nmearl I only checked when I change them from CubeViz.  Thanks for checking.

**Comment by brechmos-stsci** [comment]
Each time @kassin and I have talked about this ticket it was related to the lack of automatically setting the range (both x and y) on the graph when plots appear or disappear, sorry that wasn't clear.

What I believe is happening is that pyqtgraph (in specviz) does an autoRange (to set the "proper" range of the x and y axes) but it is doing it for all spectra, not just *displayed* spectra.  There is also a padding that is happening which maybe should be set to 0 so that the whole graph space is used to display the spectrum.

**Comment by brechmos-stsci** [comment]
Going to open a new ticket on the specviz auto range issue.  https://github.com/spacetelescope/cubeviz/issues/330
